### ISSUE TITLE
ergonomic periodic tasks

### ISSUE THREAD

**Issue by neonphog** [holochain/lib3h#465] opened 2019-10-08 22:23 UTC
There is a start at periodic tasks in ghost_system and in ghost_tracker, but they are hard to work with from the perspective of an actor / an actor's owner.

Maybe the periodic task wrapper doesn't even belong in ghost_tracker.

Figure out a good way to handle periodic tasks from an actor perspective and implement it.

**Comment by zippy** [comment] 2019-10-09 16:02
duplicate of #288

**Closed by zippy** 2019-10-09 16:02 UTC
