### ISSUE TITLE
[REPO] Logging Backend Usable by lib3h and holochain-rust

### ISSUE THREAD

**Issue by neonphog** [holochain/lib3h#16] opened 2019-05-10 14:48 UTC
As a developer, I wand to see networking related logging so that I can receive feedback on the state of the system.

- [ ] - Simple macros so adding logging to modules is trivial
- [ ] - Configurable output channel (allow stdout / stderr / file)
- [ ] - Configurable output filter (supports filter / coloring functionality currently in use by holochain-rust)

**Comment by dymayday** [comment] 2019-05-12 23:56
This is [the one](https://github.com/holochain/n3h/tree/master/lib/tweetlog) you're talking about right ?

**Comment by neonphog** [comment] 2019-05-13 14:52
@dymayday - that's the javascript version, yep. But it may make more sense to evaluate the Rust version in the net crate here: https://github.com/holochain/holochain-rust/blob/develop/net/src/tweetlog.rs

**Comment by zippy** [comment] 2019-05-24 17:53
closing as this is a duplicate of #29

**Closed by zippy** 2019-05-24 17:53 UTC
